export type IReadSearchAutoCompleteType =
  | "READING_SEARCH_AUTO_COMPLETE"
  | "READING_SEARCH_AUTO_COMPLETE_SUCCESS"
  | "READING_SEARCH_AUTO_COMPLETE_FAILURE";

export const READING_SEARCH_AUTO_COMPLETE: IReadSearchAutoCompleteType =
  "READING_SEARCH_AUTO_COMPLETE";
export const READING_SEARCH_AUTO_COMPLETE_SUCCESS: IReadSearchAutoCompleteType =
  "READING_SEARCH_AUTO_COMPLETE_SUCCESS";
export const READING_SEARCH_AUTO_COMPLETE_FAILURE: IReadSearchAutoCompleteType =
  "READING_SEARCH_AUTO_COMPLETE_FAILURE";
